### ISSUE TITLE
cant connect to mysql at 127.0.0.1

### ISSUE THREAD

**Issue by shankha117** [thelenilson/python-rest-ddd#1]
I have a falcon app which uses pony orm for mysql.
I am binding the db using this--
db.bind(provider='mysql', user='shankha', password='shankhaSQL@123', host='127.0.0.1', database='smart_senseV2')
In my Docker file (my_falcon_app:0.1) I have -

EXPOSE 8081
CMD ["gunicorn", "--reload", "routes:api", "-b:8081"]
My Docker-compose looks like this-

version: "3"
services:
  app:
    image: my_falcon_app:0.1
    links:
      - my-db
    ports:
      - "8081:8081"

  my-db:
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_1
      MYSQL_USER: root
      MYSQL_PASSWORD: password
 
    volumes:
      - ./SQP_SCRIPTS:/docker-entrypoint-initdb.d
      - ./DB_DATA:/var/lib/mysql:rw
      - ./DB_config/mysqld.conf:/etc/mysql/mysql.conf.d/mysqld.cnf
config_file--

[mysqld]
pid-file        = /var/run/mysqld/mysqld.pid
socket          = /var/run/mysqld/mysqld.sock
bind-address   = 0.0.0.0
the container for DB gets created but the app crashes every time,
error message:
pony.orm.dbapiprovider.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)")
app_ exited with code 3

CAN YOU PLEASE HELP!

**Comment by thelenilson** [comment]
Hey there,
First of all, sorry for taking too long to answer you, I haven't been looking in my repositories lately.
Did you change the port on pony ORM? It seems that you're forwarding the port to 3308 but in your `db.bind` code you're not setting the port.
